# Generated by Django 4.2.17 on 2026-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallisting',
            name='animal_type',
            field=models.CharField(choices=[('KUCUKBAS', 'Küçükbaş'), ('BUYUKBAS', 'Büyükbaş')], help_text='Type of animal (small or large)', max_length=10),
        ),
    ]
