# Generated by Django 4.2.17 on 2026-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_animallisting_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this listing has been viewed'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='animal_type',
            field=models.CharField(choices=[('SMALL', 'Küçükbaş'), ('BUYUKBAS', 'Büyükbaş')], help_text='Küçükbaş veya Büyükbaş', max_length=10, verbose_name='Hayvan Grubu'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='species',
            field=models.CharField(blank=True, help_text='(Deprecated) Eski tür alanı - kullanılmamalı', max_length=50, null=True, verbose_name='Tür'),
        ),
    ]
