# Generated by Django 4.2.17 on 2026-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animallisting_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order of the image (0 = first)'),
        ),
        migrations.AlterField(
            model_name='animalimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Is this the primary image for the listing?'),
        ),
    ]
