# Generated by Django 4.2.17 on 2026-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('FAVORITED_LISTING', 'Favorited Listing'), ('LISTING_UPDATED', 'Listing Updated'), ('PRICE_CHANGED', 'Price Changed'), ('APPOINTMENT_REQUESTED', 'Appointment Requested'), ('APPOINTMENT_APPROVED', 'Appointment Approved'), ('APPOINTMENT_REJECTED', 'Appointment Rejected'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled')], help_text='Type of notification', max_length=50),
        ),
    ]
