# Generated by Django 4.2.17 on 2026-01-14 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_animalimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Business or butcher name', max_length=255)),
                ('city', models.CharField(help_text='City where butcher operates', max_length=100)),
                ('services', models.JSONField(default=list, help_text='List of services offered')),
                ('price_range', models.CharField(blank=True, help_text="Price range (e.g., '500-1000')", max_length=50)),
                ('rating', models.FloatField(default=0.0, help_text='Average rating (0-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether accepting appointments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='User with BUTCHER role', on_delete=django.db.models.deletion.CASCADE, related_name='butcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'butcher profile',
                'verbose_name_plural': 'butcher profiles',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Appointment date')),
                ('time', models.TimeField(help_text='Appointment time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Appointment status', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('butcher', models.ForeignKey(help_text='Butcher profile', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='butchers.butcherprofile')),
                ('listing', models.ForeignKey(blank=True, help_text='Related animal listing (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='animals.animallisting')),
                ('user', models.ForeignKey(help_text='Customer requesting appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['butcher', 'status'], name='butchers_ap_butcher_032c77_idx'), models.Index(fields=['user', '-created_at'], name='butchers_ap_user_id_88748a_idx')],
            },
        ),
    ]
