# Generated by Django 4.2.17 on 2026-01-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('butcher', 'date', 'time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['butcher', 'date', 'time'], name='butchers_ap_butcher_1d2c53_idx'),
        ),
    ]
