# Generated by Django 4.2.17 on 2026-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchers', '0002_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=1, help_text='Years of experience'),
        ),
    ]
