# Generated by Django 4.2.17 on 2026-01-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0004_alter_animallisting_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City where partnership is sought', max_length=100)),
                ('person_count', models.PositiveIntegerField(help_text='Number of partners needed')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, help_text='Optional: associated animal listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='animals.animallisting')),
                ('creator', models.ForeignKey(help_text='The buyer who created this partnership listing', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership Listing',
                'verbose_name_plural': 'Partnership Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
