# Generated by Django 4.2.17 on 2026-01-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
        migrations.CreateModel(
            name='EmailOTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address to verify', max_length=254)),
                ('otp_hash', models.CharField(help_text='Hashed OTP code (never store plaintext)', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='When the OTP was successfully verified', null=True)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('resend_count', models.IntegerField(default=0, help_text='Number of times OTP was resent')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='When OTP was last sent', null=True)),
                ('purpose', models.CharField(default='REGISTER_EMAIL_VERIFY', help_text='Purpose of this OTP', max_length=50)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user (null if not yet registered)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP Verification',
                'verbose_name_plural': 'Email OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'consumed_at'], name='accounts_em_email_3f2556_idx'), models.Index(fields=['email', 'purpose', 'expires_at'], name='accounts_em_email_e97a5c_idx')],
            },
        ),
    ]
