# Generated by Django 4.2.17 on 2026-01-25 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_verified_emailotpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Verified email address', max_length=254)),
                ('token_hash', models.CharField(help_text='Hashed verification token (never store plaintext)', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='When the token was used for registration', null=True)),
                ('purpose', models.CharField(default='REGISTER_EMAIL', help_text='Purpose of this verification token', max_length=50)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'consumed_at'], name='accounts_em_email_6bddb8_idx'), models.Index(fields=['email', 'purpose', 'expires_at'], name='accounts_em_email_1f84bd_idx')],
            },
        ),
    ]
